spring:
  application:
    name: reppl

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # Spring Session (Redis)
  session:
    store-type: redis
    timeout: ${SESSION_TIMEOUT}

  # Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Kafka Topic
kafka:
  topic:
    job-request: ${KAFKA_TOPIC_JOB_REQUEST}
    job-request.partitions: ${KAFKA_TOPIC_JOB_REQUEST_PARTITIONS}
    job-progress: ${KAFKA_TOPIC_JOB_PROGRESS}
    job-progress.partitions: ${KAFKA_TOPIC_JOB_PROGRESS_PARTITIONS}

# AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
